# Autoencoder Configuration
_target_: src.models.autoencoder.AutoEncoder

# Model Architecture
resolution: 256
in_channels: 1
ch: 2
out_ch: 1
ch_mult: [2, 4, 8, 16]
num_res_blocks: 4
z_channels: 4
scale_factor: 1.0
shift_factor: 0.0

# Diffusion Specific
beta_schedule:
  _target_: src.models.diffusion.CosineBetaScheduler
  num_timesteps: 1000
  s: 0.008

# Training Memory Management
accumulation_steps: 4  # batch_size // max_batch_size