# Training Configuration
epochs: 10
batch_size: 8
max_batch_size: 2
val_split: 0.1

# Optimizer
optimizer:
  _target_: tensorflow.keras.optimizers.Adam
  learning_rate: 0.001
  beta_1: 0.9
  beta_2: 0.999

# Loss Function
loss:
  _target_: tensorflow.keras.losses.MeanSquaredError

# Metrics
metrics:
  - _target_: tensorflow.keras.metrics.MeanAbsoluteError

# Callbacks
callbacks:
  early_stopping:
    _target_: tensorflow.keras.callbacks.EarlyStopping
    monitor: "val_loss"
    patience: 10
    restore_best_weights: true
    
  reduce_lr:
    _target_: tensorflow.keras.callbacks.ReduceLROnPlateau
    monitor: "val_loss"
    factor: 0.2
    patience: 5
    min_delta: 0.001

  model_checkpoint:
    monitor: "val_loss"
    save_best_only: true
    verbose: 1