# Main Configuration File
defaults:
  - model: autoencoder
  - training: default
  - data: default
  - _self_

# Project Settings
project_name: "neutron_star_diffusion"
experiment_name: "baseline_v1"
random_seed: 42

# Paths
data:
  root_path: "/mnt/rafast/miler"
  raw_data: "${data.root_path}/new_normalized_star/test/"
  processed_data: "${data.root_path}/ml_data_pics.npy"
  checkpoint_dir: "${data.root_path}/checkpoints"
  logs_dir: "${data.root_path}/logs"

# Hardware
hardware:
  num_workers: 50
  threads_per_worker: 1
  memory_limit: "4GB"
  gpu_memory_growth: true

# Logging
logging:
  level: "INFO"
  use_wandb: true
  use_tensorboard: true
  log_every_n_steps: 100
  save_every_n_epochs: 10